'use strict';

/**
 * Created by baohg on 20/06/2016.
 */
//var cheerio = require('cheerio');
//
//var $ = cheerio.load('<span id="disabled_TAR.ACCT.NAME" class="disabled_dealbox" style="width:2.53em;">VND-TGTT-HO VIET THUYEN</span>');
//
//console.log($('span[id="disabled_TAR.ACCT.NAME"]').text());
var request = require('request');

var param = {
  url: 'https://ib.techcombank.com.vn/servlet/BrowserServlet',
  headers: {Cookie: '_ga=GA1.3.192040917.1465784328; tcbtodayexpire=1; tcbtodaycount=0; JSESSIONID=0000_oziqdn4vrqxuFUv-gZra7i:-1; NSC_WTfswfs_BSDJC_Xfc_TTM=ffffffff09681f4d45525d5f4f58455e445a4a421548'},
  form: {
    formToken: 'A384CAD336A243987739000F4FD7DB9C1BD1D2BDB7BBBEA78C',
    toggle: '',
    command: 'globusCommand',
    requestType: 'OFS.APPLICATION',
    ofsOperation: 'PROCESS',
    ofsFunction: 'I',
    ofsMessage: '',
    GTSControl: '',
    routineName: '',
    routineArgs: '',
    cfNavOperation: '',
    unlock: '',
    activeTab: 'tab1',
    SaveChangesText: 'Changes Not Saved',
    RecordDelText: 'Are you sure you want to delete the transaction?',
    expansionHistory: '',
    version: ',AI.QCK.INT.CON.TCB',
    application: 'FUNDS.TRANSFER',
    enableDealSlip: '',
    decrypt: '',
    addGroupTab: '',
    deleteGroupTab: '',
    expandableTab: '',
    tabEnri: '',
    product: 'FT',
    name: '',
    operation: '',
    windowName: 'MainBody042385725902',
    toolbarTarget: '',
    overridesAccepted: 'YES',
    overridesApproved: 'NO',
    focus: '',
    ContractStatus: 'CHG',
    windowUnqRef: '',
    editVersion: 'FUNDS.TRANSFER,AI.QCK.INT.INP.TCB',
    confirmVersion: 'FUNDS.TRANSFER,AI.QCK.INT.CON.TCB',
    previewVersion: 'FUNDS.TRANSFER,AI.QCK.INT.PRE.TCB',
    enqname: '',
    enqaction: '',
    dropfield: '',
    previousEnqs: '',
    previousEnqTitles: '',
    clientStyleSheet: '',
    windowSizes: '0:0:800:500',
    changedFields: '',
    newCommands: '',
    screenMode: 'I',
    lockArgs: '',
    RecordRead: '1',
    PastedDeal: '',
    allowResize: 'YES',
    companyId: 'VN0010001',
    company: 'BNK-TECHCOMBANK HOI SO',
    user: 'HOVIETTHUYEN',
    transSign: '',
    skin: 'arc-ib',
    today: '21/06/2016',
    release: 'R14',
    compScreen: 'COMPOSITE.SCREEN_HOVIETTHUYEN_042385725903',
    reqTabid: '',
    compTargets: 'ALL_MainBody042385725902|',
    EnqParentWindow: '',
    timing: '1056-13-19-1024-2',
    pwprocessid: '',
    language: 'VN',
    languages: 'GB,VN',
    savechanges: 'YES',
    staticId: '',
    lockDateTime: '160621155450',
    popupDropDown: 'true',
    allowcalendar: '',
    allowdropdowns: '',
    allowcontext: 'NO',
    nextStage: '',
    maximize: '',
    showStatusInfo: 'NO',
    languageUndefined: 'Language Code Not Defined',
    expandMultiString: 'Expand Multi Value',
    deleteMultiString: 'Delete Value',
    expandSubString: 'Expand Sub Value',
    clientExpansion: 'true',
    WS_parentWindow: '',
    WS_parent: '',
    WS_dropfield: '',
    WS_doResize: '',
    WS_initState: 'FT,AI.QCK.INT.INP.TCB I F3',
    WS_PauseTime: '',
    WS_multiPane: 'false',
    WS_replaceAll: '',
    WS_parentComposite: 'FUNCTION861255725604',
    WS_delMsgDisplayed: '',
    'overrideText:Quy khach bam "Thuc hien" de xac nhan giao dich:value': 'YES',
    transactionId: 'FT16173506129669',
    'fieldName:DEBIT.ACCT.NO': '19028024924011',
    'fieldName:SRC.ACCT.NAME': 'TIEN GUI THANH TOAN',
    'fieldName:SRC.CURR.BAL': 'VND 174,213',
    'fieldName:CREDIT.ACCT.NO': '19030322434011',
    'fieldName:TAR.ACCT.NAME': 'VND-TGTT-NGUYEN THANH DIEU',
    'fieldName:PAYMENT.DETAILS:1': 'TECHCOMBANK',
    'fieldName:DEBIT.AMOUNT': '50,000',
    'fieldName:DEBIT.CURRENCY': 'VND',
    'fieldName:PROCESSING.DATE': '21/06/2016',
    'fieldName:CREDIT.THEIR.REF': '',
    'fieldName:PAY.DETAILS': 'alo alo',
    'fieldName:LOCAL.CHARGE.AMT': '1,100',
    overridesPresent: 'YES',
    WS_FragmentName: 'MainBody042385725902'
  }
}
var fs = require('fs');
request.post(param, (e, r, b)=> {
  console.log(r.headers);
  console.log(b);
  fs.writeFile('abc.html', b);
})